[package]
name = "trace-err"
version = "0.1.0"
edition.workspace = true

[lib]
path = "lib.rs"
crate-type = ["rlib"]

[dependencies]
tracing = "0.1.40"

[dev-dependencies]
tracing-subscriber = "0.3.18"
