name: Publish crate

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - uses: katyo/publish-crates@v2
      with:
        dry-run: true  
        #registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
